spring:
  config:
    import: "file:src/main/resources/.env[.properties]"
  application:
    name: first-rest-app
  datasource:
    url: jdbc:postgresql://localhost:5435/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
logging:
  file:
    path: ./../../../logs/
