spring:
  config:
    import: "file:.env[.properties]"
  application:
    name: first-rest-app
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
logging:
  file:
    path: ./../../../logs/
