spring:
  application:
    name: first-rest-app
  datasource:
    url: jdbc:postgresql://localhost:5435/repair_service
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

